// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/transactions.proto

package transactionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Coinid               string                 `protobuf:"bytes,1,opt,name=coinid,proto3" json:"coinid,omitempty"`
	Userid               string                 `protobuf:"bytes,2,opt,name=userid,proto3" json:"userid,omitempty"`
	Dataid               string                 `protobuf:"bytes,3,opt,name=dataid,proto3" json:"dataid,omitempty"`
	Coinused             float64                `protobuf:"fixed64,4,opt,name=coinused,proto3" json:"coinused,omitempty"`
	TransactionTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=transaction_timestamp,json=transactionTimestamp,proto3" json:"transaction_timestamp,omitempty"`
	ExpiryDate           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	PlatformName         string                 `protobuf:"bytes,7,opt,name=platform_name,json=platformName,proto3" json:"platform_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_proto_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetCoinid() string {
	if x != nil {
		return x.Coinid
	}
	return ""
}

func (x *CreateTransactionRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *CreateTransactionRequest) GetDataid() string {
	if x != nil {
		return x.Dataid
	}
	return ""
}

func (x *CreateTransactionRequest) GetCoinused() float64 {
	if x != nil {
		return x.Coinused
	}
	return 0
}

func (x *CreateTransactionRequest) GetTransactionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTimestamp
	}
	return nil
}

func (x *CreateTransactionRequest) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *CreateTransactionRequest) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

type Transaction struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Coinid               string                 `protobuf:"bytes,2,opt,name=coinid,proto3" json:"coinid,omitempty"`
	Userid               string                 `protobuf:"bytes,3,opt,name=userid,proto3" json:"userid,omitempty"`
	Dataid               string                 `protobuf:"bytes,4,opt,name=dataid,proto3" json:"dataid,omitempty"`
	Coinused             float64                `protobuf:"fixed64,5,opt,name=coinused,proto3" json:"coinused,omitempty"`
	TransactionTimestamp *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=transaction_timestamp,json=transactionTimestamp,proto3" json:"transaction_timestamp,omitempty"`
	ExpiryDate           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	PlatformName         string                 `protobuf:"bytes,8,opt,name=platform_name,json=platformName,proto3" json:"platform_name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetCoinid() string {
	if x != nil {
		return x.Coinid
	}
	return ""
}

func (x *Transaction) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *Transaction) GetDataid() string {
	if x != nil {
		return x.Dataid
	}
	return ""
}

func (x *Transaction) GetCoinused() float64 {
	if x != nil {
		return x.Coinused
	}
	return 0
}

func (x *Transaction) GetTransactionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTimestamp
	}
	return nil
}

func (x *Transaction) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *Transaction) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

var File_proto_transactions_proto protoreflect.FileDescriptor

const file_proto_transactions_proto_rawDesc = "" +
	"\n" +
	"\x18proto/transactions.proto\x12\x0ftransactions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x02\n" +
	"\x18CreateTransactionRequest\x12\x16\n" +
	"\x06coinid\x18\x01 \x01(\tR\x06coinid\x12\x16\n" +
	"\x06userid\x18\x02 \x01(\tR\x06userid\x12\x16\n" +
	"\x06dataid\x18\x03 \x01(\tR\x06dataid\x12\x1a\n" +
	"\bcoinused\x18\x04 \x01(\x01R\bcoinused\x12O\n" +
	"\x15transaction_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14transactionTimestamp\x12;\n" +
	"\vexpiry_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x12#\n" +
	"\rplatform_name\x18\a \x01(\tR\fplatformName\"\xb4\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06coinid\x18\x02 \x01(\tR\x06coinid\x12\x16\n" +
	"\x06userid\x18\x03 \x01(\tR\x06userid\x12\x16\n" +
	"\x06dataid\x18\x04 \x01(\tR\x06dataid\x12\x1a\n" +
	"\bcoinused\x18\x05 \x01(\x01R\bcoinused\x12O\n" +
	"\x15transaction_timestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x14transactionTimestamp\x12;\n" +
	"\vexpiry_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x12#\n" +
	"\rplatform_name\x18\b \x01(\tR\fplatformName2l\n" +
	"\fTransactions\x12\\\n" +
	"\x11CreateTransaction\x12).transactions.v1.CreateTransactionRequest\x1a\x1c.transactions.v1.TransactionB>Z<transaction-service/proto/gen/transactions/v1;transactionsv1b\x06proto3"

var (
	file_proto_transactions_proto_rawDescOnce sync.Once
	file_proto_transactions_proto_rawDescData []byte
)

func file_proto_transactions_proto_rawDescGZIP() []byte {
	file_proto_transactions_proto_rawDescOnce.Do(func() {
		file_proto_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transactions_proto_rawDesc), len(file_proto_transactions_proto_rawDesc)))
	})
	return file_proto_transactions_proto_rawDescData
}

var file_proto_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_transactions_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil), // 0: transactions.v1.CreateTransactionRequest
	(*Transaction)(nil),              // 1: transactions.v1.Transaction
	(*timestamppb.Timestamp)(nil),    // 2: google.protobuf.Timestamp
}
var file_proto_transactions_proto_depIdxs = []int32{
	2, // 0: transactions.v1.CreateTransactionRequest.transaction_timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: transactions.v1.CreateTransactionRequest.expiry_date:type_name -> google.protobuf.Timestamp
	2, // 2: transactions.v1.Transaction.transaction_timestamp:type_name -> google.protobuf.Timestamp
	2, // 3: transactions.v1.Transaction.expiry_date:type_name -> google.protobuf.Timestamp
	0, // 4: transactions.v1.Transactions.CreateTransaction:input_type -> transactions.v1.CreateTransactionRequest
	1, // 5: transactions.v1.Transactions.CreateTransaction:output_type -> transactions.v1.Transaction
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_transactions_proto_init() }
func file_proto_transactions_proto_init() {
	if File_proto_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transactions_proto_rawDesc), len(file_proto_transactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transactions_proto_goTypes,
		DependencyIndexes: file_proto_transactions_proto_depIdxs,
		MessageInfos:      file_proto_transactions_proto_msgTypes,
	}.Build()
	File_proto_transactions_proto = out.File
	file_proto_transactions_proto_goTypes = nil
	file_proto_transactions_proto_depIdxs = nil
}
